services:
  - type: web
    name: telegram-weather-bot
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # хранится в Render → Environment
      - key: WEBHOOK_URL
        sync: false  # https://telegram-weather-bot-i1y8.onrender.com
