services:
  - type: web
    name: telegram-weather-bot
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # set in Render dashboard
      - key: WEBHOOK_URL
        sync: false  # set to https://<your-service>.onrender.com after first deploy
      - key: PORT
        value: 10000  # Render sets PORT automatically; this default is fine
